// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cmd } from '../tkfm-mech/cmd.js';


export class CharacterRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CharacterRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():number {
  return this.bb!.readUint32(this.bb_pos);
}

rarity():number {
  return this.bb!.readUint8(this.bb_pos + 4);
}

element():number {
  return this.bb!.readUint8(this.bb_pos + 5);
}

role():number {
  return this.bb!.readUint8(this.bb_pos + 6);
}

cd():number {
  return this.bb!.readUint8(this.bb_pos + 7);
}

hp():number {
  return this.bb!.readUint32(this.bb_pos + 8);
}

atk():number {
  return this.bb!.readUint32(this.bb_pos + 12);
}

atkMag():number {
  return this.bb!.readUint16(this.bb_pos + 16);
}

ultMag():number {
  return this.bb!.readUint16(this.bb_pos + 18);
}

seq():number {
  return this.bb!.readUint16(this.bb_pos + 20);
}

usedCmds():number {
  return this.bb!.readUint16(this.bb_pos + 22);
}

exclCount():number {
  return this.bb!.readUint8(this.bb_pos + 24);
}

_Pad3():number {
  return this.bb!.readUint8(this.bb_pos + 25);
}

exclTypes(index: number):number|null {
    return this.bb!.readUint16(this.bb_pos + 26 + index * 2);
}

mnc(index: number):number|null {
    return this.bb!.readFloat64(this.bb_pos + 40 + index * 8);
}

slotInit(index: number):number|null {
    return this.bb!.readInt32(this.bb_pos + 120 + index * 4);
}

flags(index: number):number|null {
    return this.bb!.readUint8(this.bb_pos + 136 + index);
}

cmds(index: number, obj?:Cmd):Cmd|null {
    return (obj || new Cmd()).__init(this.bb_pos + 152 + index * 104, this.bb!);
}

static sizeOf():number {
  return 26776;
}

static createCharacterRecord(builder:flatbuffers.Builder, id: number, rarity: number, element: number, role: number, cd: number, hp: number, atk: number, atkMag: number, ultMag: number, seq: number, usedCmds: number, exclCount: number, _pad3: number, exclTypes: number[], mnc: number[], slotInit: number[], flags: number[], cmds: any[]):flatbuffers.Offset {
  builder.prep(8, 26776);

  for (let i = 255; i >= 0; --i) {
    const item = cmds?.[i];

    Cmd.createCmd(builder,
    item?.op,
    item?.tgt,
    item?.tgtN,
    item?._Pad,
    (item?.cond?.kind ?? 0),
    (item?.cond?.cmp ?? 0),
    (item?.cond?.nameIdx ?? 0),
    (item?.cond?.a ?? 0),
    (item?.cond?.b ?? 0),
    item?.ps
    );
  }


  for (let i = 15; i >= 0; --i) {
    builder.writeInt8((flags?.[i] ?? 0));

  }


  for (let i = 3; i >= 0; --i) {
    builder.writeInt32((slotInit?.[i] ?? 0));

  }


  for (let i = 9; i >= 0; --i) {
    builder.writeFloat64((mnc?.[i] ?? 0));

  }

  builder.pad(6);

  for (let i = 3; i >= 0; --i) {
    builder.writeInt16((exclTypes?.[i] ?? 0));

  }

  builder.writeInt8(_pad3);
  builder.writeInt8(exclCount);
  builder.writeInt16(usedCmds);
  builder.writeInt16(seq);
  builder.writeInt16(ultMag);
  builder.writeInt16(atkMag);
  builder.writeInt32(atk);
  builder.writeInt32(hp);
  builder.writeInt8(cd);
  builder.writeInt8(role);
  builder.writeInt8(element);
  builder.writeInt8(rarity);
  builder.writeInt32(id);
  return builder.offset();
}

}
