// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cmp } from '../tkfm-mech/cmp.js';
import { Cond } from '../tkfm-mech/cond.js';
import { CondKind } from '../tkfm-mech/cond-kind.js';
import { Op } from '../tkfm-mech/op.js';
import { Param } from '../tkfm-mech/param.js';
import { Target } from '../tkfm-mech/target.js';


export class Cmd {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Cmd {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

op():Op {
  return this.bb!.readUint8(this.bb_pos);
}

tgt():Target {
  return this.bb!.readUint8(this.bb_pos + 1);
}

tgtN():number {
  return this.bb!.readUint8(this.bb_pos + 2);
}

_Pad():number {
  return this.bb!.readUint8(this.bb_pos + 3);
}

cond(obj?:Cond):Cond|null {
  return (obj || new Cond()).__init(this.bb_pos + 4, this.bb!);
}

ps(index: number, obj?:Param):Param|null {
    return (obj || new Param()).__init(this.bb_pos + 16 + index * 8, this.bb!);
}

static sizeOf():number {
  return 104;
}

static createCmd(builder:flatbuffers.Builder, op: Op, tgt: Target, tgtN: number, _pad: number, cond_kind: CondKind, cond_cmp: Cmp, cond_nameIdx: number, cond_a: number, cond_b: number, ps: any[]):flatbuffers.Offset {
  builder.prep(4, 104);

  for (let i = 10; i >= 0; --i) {
    const item = ps?.[i];

    Param.createParam(builder,
    item?.tag,
    item?._Pad,
    item?._Pad2,
    item?.i
    );
  }

  builder.prep(4, 12);
  builder.writeInt32(cond_b);
  builder.writeInt32(cond_a);
  builder.writeInt16(cond_nameIdx);
  builder.writeInt8(cond_cmp);
  builder.writeInt8(cond_kind);
  builder.writeInt8(_pad);
  builder.writeInt8(tgtN);
  builder.writeInt8(tgt);
  builder.writeInt8(op);
  return builder.offset();
}

}
