// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Cmp {
  Eq = 0,
  Ne = 1,
  Gt = 2,
  Ge = 3,
  Lt = 4,
  Le = 5
}
