// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cmp } from '../tkfm-mech/cmp.js';
import { CondKind } from '../tkfm-mech/cond-kind.js';


export class Cond {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Cond {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

kind():CondKind {
  return this.bb!.readUint8(this.bb_pos);
}

cmp():Cmp {
  return this.bb!.readUint8(this.bb_pos + 1);
}

nameIdx():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

a():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

b():number {
  return this.bb!.readInt32(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createCond(builder:flatbuffers.Builder, kind: CondKind, cmp: Cmp, nameIdx: number, a: number, b: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeInt32(b);
  builder.writeInt32(a);
  builder.writeInt16(nameIdx);
  builder.writeInt8(cmp);
  builder.writeInt8(kind);
  return builder.offset();
}

}
