// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CharacterRecord } from '../tkfm-mech/character-record.js';


export class MechanismTable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MechanismTable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMechanismTable(bb:flatbuffers.ByteBuffer, obj?:MechanismTable):MechanismTable {
  return (obj || new MechanismTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMechanismTable(bb:flatbuffers.ByteBuffer, obj?:MechanismTable):MechanismTable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MechanismTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('TKFM');
}

version():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

charCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

records(index: number, obj?:CharacterRecord):CharacterRecord|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CharacterRecord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 26776, this.bb!) : null;
}

recordsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

names(index: number):string
names(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
names(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

namesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMechanismTable(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt16(0, version, 0);
}

static addCharCount(builder:flatbuffers.Builder, charCount:number) {
  builder.addFieldInt16(1, charCount, 0);
}

static addRecords(builder:flatbuffers.Builder, recordsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, recordsOffset, 0);
}

static startRecordsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(26776, numElems, 8);
}

static addNames(builder:flatbuffers.Builder, namesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, namesOffset, 0);
}

static createNamesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startNamesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMechanismTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishMechanismTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'TKFM');
}

static finishSizePrefixedMechanismTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'TKFM', true);
}

static createMechanismTable(builder:flatbuffers.Builder, version:number, charCount:number, recordsOffset:flatbuffers.Offset, namesOffset:flatbuffers.Offset):flatbuffers.Offset {
  MechanismTable.startMechanismTable(builder);
  MechanismTable.addVersion(builder, version);
  MechanismTable.addCharCount(builder, charCount);
  MechanismTable.addRecords(builder, recordsOffset);
  MechanismTable.addNames(builder, namesOffset);
  return MechanismTable.endMechanismTable(builder);
}
}
