// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Tag } from '../tkfm-mech/tag.js';


export class Param {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Param {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

tag():Tag {
  return this.bb!.readUint8(this.bb_pos);
}

_Pad():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

_Pad2():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

i():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createParam(builder:flatbuffers.Builder, tag: Tag, _pad: number, _pad2: number, i: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(i);
  builder.writeInt16(_pad2);
  builder.writeInt8(_pad);
  builder.writeInt8(tag);
  return builder.offset();
}

}
