// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Tag {
  None = 0,
  NameIdx = 1,
  TypeIdx = 2,
  Fix = 3,
  Always = 4,
  Bool = 5,
  Target = 6,
  ExprAtkRef = 7,
  TernLeader = 8,
  SlotRef = 9,
  HookId = 10,
  ModeId = 11,
  PhaseId = 12,
  FlagId = 13,
  ExprHp = 14,
  TempRef = 15,
  ExprSize = 16,
  CountVal = 17,
  ExprNestByType = 19,
  NameCat = 20,
  TempVal = 21,
  ExprAtkComp = 22
}
