// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Target {
  None = 0,
  Self = 1,
  All = 2,
  Boss = 3,
  CompN = 4,
  LoopI = 5,
  LoopUp = 6,
  LowestHp = 7,
  TempUnit = 8,
  BossHitTarget = 9
}
